name: Auto update

env:
  BUILDER_TOOLS_URL: https://github.com/flatpak/flatpak-builder-tools.git
  BUILDER_TOOLS_BRANCH: master

on:
  schedule:
    - cron: "45 6 * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
      - name: Configure safe directory for Git
        run: git config --global --add safe.directory /__w/net.hovancik.Stretchly/net.hovancik.Stretchly

      - name: Install dependencies
        run: |
          sudo dnf -y install jq npm pipx python3-aiohttp python3-pip
          python3 -m pipx install yq

      - uses: actions/checkout@v3
        with:
          set-safe-directory: '/__w/net.hovancik.Stretchly/net.hovancik.Stretchly'

      - name: Download flatpak-builder-tools
        run: |
          git clone -b ${BUILDER_TOOLS_BRANCH} \
                       ${BUILDER_TOOLS_URL} \
                       flatpak-builder-tools

      - name: Install flatpak-node-generator
        run: |
          pipx install flatpak-builder-tools/node
          pipx ensurepath

      - name: Create and switch to working branch
        run: git switch -c update-python-modules-$(git rev-parse --short HEAD)

      - name: Pull down the Stretchly repository
        uses: actions/checkout@v3
        with:
          repository: hovancik/stretchly
          path: stretchly
          fetch-depth: 0

      - name: Checkout the current Stretchly version
        run: git -C stretchly switch -d "$(yq -r '.[].commit' stretchly-sources.yaml)"

      - name: Update Node dependencies
        run: |
          set -e
          flatpak-node-generator npm stretchly/package-lock.json
          git diff --staged --quiet
          if test $? -ne 0
          then
            git add -- generated-sources.json
            git commit -m "Update Node dependencies"
            git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          fi
